### ISSUE TITLE
ModuleNotFoundError: No module named 'petrel_client'

### ISSUE THREAD

**Issue by TingqiaoXu** [jyFengGoGo/InstructDet#3]
How to install petrel_client? It cannot be installed by pip install

**Comment by jyFengGoGo** [comment]
Thank you for pointing this issue out！
'petrel_client' is an internal package simply for loading data from buckets and it is unnecessary if the images are saved local. 
Now we have updated the code and removed this import.

**Comment by jyFengGoGo** [comment]
> How to install petrel_client? It cannot be installed by pip install

Thank you for pointing this issue out！
'petrel_client' is an internal package simply for loading data from buckets and it is unnecessary if the images are saved local. 
Now we have updated the code and removed this import.
