### ISSUE TITLE
Dependency conflicts of transformers

### ISSUE THREAD

**Issue by guyguy404** [jyFengGoGo/InstructDet#4]
I encounter the following error when I use pip to install module dependencies.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fschat 0.2.15 requires transformers<4.29.0,>=4.28.0, but you have transformers 4.31.0 which is incompatible.
```

fschat 0.2.15 requires transformers<4.29.0,>=4.28.0
llava 0.1.0 requires transformers==4.31.0

How to solve this dependency conflict?

**Comment by jyFengGoGo** [comment]
> I encounter the following error when I use pip to install module dependencies.
> 
> ```
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> fschat 0.2.15 requires transformers<4.29.0,>=4.28.0, but you have transformers 4.31.0 which is incompatible.
> ```
> 
> fschat 0.2.15 requires transformers<4.29.0,>=4.28.0 llava 0.1.0 requires transformers==4.31.0
> 
> How to solve this dependency conflict?

Even though there does exist a version conflict, transformers==4.31.0 works fine for fschat.
